import Head from "next/head";

// CSS stands for Cascading Style Sheets.

// CSS is a language that web developers use to style web pages.

// CSS is a lot like writing the design for a recipe.

// There are different properties that you can use to style all kinds of things.

// Hold alt and click on the link below to see what this page looks like.
// http://localhost:3000/css

export default function Style() {
  return (
    <>
      <Head>
        <title>CSS</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>CSS</h1>
        <p>
          This is going to be the first task where we work in more than 1 file.
        </p>
        <p>
          Open up the file <code>src/styles/tags.css</code> and look around.
        </p>
        <p>
          Try changing the color of the text in the <code>p</code> tag.
        </p>
      </main>
    </>
  );
}
