import Head from "next/head";

// HTML stands for HyperText Markup Language.
// It's the language that web pages are written in.

// HTML is a lot like writing the format for a recipe.

// There are different tags that you can use to format text, images, and links.
// Tags are like the ingredients in a recipe. They tell the computer what to do.

// Let's write a simple HTML page.

// Hold alt and click on the link below to see what this page looks like.
// http://localhost:3000/html

export default function HyperText() {
  return (
    <>
      <Head>
        <title>HTML</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>HTML</h1>
        <p>The p tag is used to write paragraphs.</p>
        <p>Each p tag creates a new paragraph.</p>
        <p>Try writing your own paragraph.</p>
        <br />
        <ul>
          <li>The ul tag is used to write an unordered list.</li>
          <li>Each li tag creates a new list item.</li>
          <li>Try writing your own list item.</li>
        </ul>
      </main>
    </>
  );
}

// Tags to try:
// - h1 to h6: This is a heading tag. It makes text bigger and bold.
// - p: This is a paragraph tag. It makes text normal size.
// - a: This is a link tag. It makes text clickable.
// - img: This is an image tag. It shows an image.
// - br: This is a line break tag. It makes a new line.
// - hr: This is a horizontal rule tag. It makes a line.
// - ul: This is an unordered list tag. It makes a list.
// - ol: This is an ordered list tag. It makes a numbered list.
// - li: This is a list item tag. It makes an item in a list (ul or ol).
// - strong: This is a strong tag. It makes text bold.
// - em: This is an emphasis tag. It makes text italic.
// - small: This is a small tag. It makes text smaller.
// - button: This is a button tag. It makes a button.
