import Head from "next/head";

// This is a comment.
// They're ignored by the computer and are just for humans to read.

// Programmers write comments to explain their code to other programmers.

// Programming is a lot like writing a recipe. You write a list of instructions
// that the computer follows to make something happen.

// This is a function. It's a list of instructions that the computer can follow.
// Functions are like recipes. They take some ingredients (called "arguments") and
// do something with them.

// This function is called "Home". It doesn't take any ingredients (arguments).
// It just returns a list of instructions to the computer.

// Hold alt and click on the link below to see what this page looks like.
// http://localhost:3000/programming

export default function Programming() {
  return (
    <>
      <Head>
        <title>Change me!</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <h1>Programming</h1>
        <p>Make changes here to see how the recipe changes.</p>
        <p>Try changing the title in the Head component.</p>
        <p>Try changing the text in the h1 component.</p>
        <p>Try adding more p components.</p>
        <p>Try adding an h2 component.</p>
        <style jsx>{`
          p {
            padding-bottom: 1rem;
          }
        `}</style>
      </main>
    </>
  );
}
